version: '3.4'

networks:
  backend:


services:
    productdb:
        container_name: product-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
        networks:
          - backend
        ports:
          - 18001:1433
    productwebapi:
        container_name: product-api
        image: ${DOCKER_REGISTRY-}productwebapi
        build:
          context: .
          dockerfile: ProductWebAPI/Dockerfile
        networks:
          - backend
        environment:
          - DB_HOST=productdb
          - DB_NAME=ProductShopDB
          - DB_SA_PASSWORD=P@ssw0rd!

    apigateway:
        container_name:  backend-shop-api-gateway
        image: ${DOCKER_REGISTRY-}apigateway
        build:
          context: .
          dockerfile: ApiGateway/Dockerfile
        ports:
          - 8001:80
        networks:
           - backend


