version: '3.4'

networks:
  backend:
  frontend:



services:
    productdb:
        container_name: product-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=P@ssw0rd!
        networks:
          - backend
        ports:
          - 18001:1433
    productwebapi:
        container_name: product-api
        image: ${DOCKER_REGISTRY-}productwebapi
        build:
          context: .
          dockerfile: ProductWebAPI/Dockerfile
        networks:
          - backend
        environment:
          - DB_HOST=productdb
          - DB_NAME=ProductShopDB
          - DB_SA_PASSWORD=P@ssw0rd!

    authenticationapi:
        container_name: authentication-api
        image: ${DOCKER_REGISTRY-}authenticationapi
        build:
          context: .
          dockerfile: AuthenticationApi/Dockerfile
        depends_on: 
          - productdb
        environment:
          - DB_HOST=productdb
          - DB_NAME=UserDB
          - DB_SA_PASSWORD=P@ssw0rd!
        networks:
           - backend

